### ISSUE TITLE
About me Grammar Errors

### ISSUE THREAD

**Issue by rammazzoti2000** [amita-roy/Portfolio#6]
The following text has some errors:

Well-organised person, problem solver, ~a person~ (**here** `a person` i**s only a repetition since person is already mentioned at the beginning of the phrase**) with high attention to detail`s`. There’s nothing I enjoy more `than` developing good websites for nice people. While I’ll never be perfect, I do my best to come close.

##

Well-organised person, problem solver, with high attention to details. There’s nothing I enjoy more than developing quality websites for nice people. While I’ll never be perfect, I do my best to come close.

**Comment by amita-roy** [comment]
Thank you so much Alex. I'll work on these errors and thank you so much once again for coming here and providing feedback.  I would say please provide your thoughts and feedback on not only this project but on upcoming as well.

**Comment by amita-roy** [comment]
I have updated the suggested changes hence closing this issue. Thanks for the feedback. 👍
